name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm install
      - run: pnpm run lint
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm install
      - run: pnpm run test
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm install
      - run: pnpm run build
      - run: pnpx semantic-release
        env:
          GH_TOKEN: ${{ secrets.RESREQ_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.RESREQ_NPM_TOKEN }}
